name: Build Spoofer

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ATL components via VS installer
      run: |
        choco install visualstudio2022-workload-vctools --no-progress
      shell: powershell

    - name: Download ImGui library
      run: |
        git clone https://github.com/ocornut/imgui.git temp_imgui
        # Копируем заголовочные и исходные файлы ImGui прямо в корень проекта, чтобы компилятор их нашел
        Copy-Item temp_imgui/*.h -Destination .
        Copy-Item temp_imgui/*.cpp -Destination .
        # Также подпапки для бэкендов DX9/Win32 если требуются
        New-Item -ItemType Directory -Force -Path imgui
        Copy-Item temp_imgui/* -Destination imgui -Recurse
      shell: powershell

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild spoofer.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Spoofer-Release
        path: x64/Release/
