name: Build Spoofer

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ATL components via VS installer
      run: |
        # Устанавливаем ATL для поддержки atlstr.h
        choco install visualstudio2022-workload-vctools --no-progress
      shell: powershell

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild spoofer.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Spoofer-Release
        path: x64/Release/
